#!/usr/bin/env python3
"""Regenerate GermanyMap.js from the deutschlandGeoJSON state borders.

The plugin never fetches geometry at runtime; this script projects and
simplifies the borders once so the shipped map is small and static.

    python3 tools/build-map.py > GermanyMap.js
"""
import json
import math
import urllib.request

SOURCE = ("https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/"
          "main/2_bundeslaender/4_niedrig.geo.json")
WIDTH = 1000.0
TOLERANCE = 1.4          # Douglas-Peucker tolerance in viewbox units
MIN_PART_RATIO = 0.015   # drop islands smaller than this share of a state's mainland

# DAWUM parliament ids; see https://api.dawum.de/
PARLIAMENTS = {
    "DE-BW": "1", "DE-BY": "2", "DE-BE": "3", "DE-BB": "4", "DE-HB": "5",
    "DE-HH": "6", "DE-HE": "7", "DE-MV": "8", "DE-NI": "9", "DE-NW": "10",
    "DE-RP": "11", "DE-SL": "12", "DE-SN": "13", "DE-ST": "14", "DE-SH": "15",
    "DE-TH": "16",
}


def simplify(points, tolerance):
    if len(points) < 3:
        return points
    keep = [False] * len(points)
    keep[0] = keep[-1] = True
    stack = [(0, len(points) - 1)]
    while stack:
        a, b = stack.pop()
        (ax, ay), (bx, by) = points[a], points[b]
        dx, dy = bx - ax, by - ay
        length = math.hypot(dx, dy) or 1e-9
        best, index = 0.0, -1
        for i in range(a + 1, b):
            px, py = points[i]
            distance = abs(dy * px - dx * py + bx * ay - by * ax) / length
            if distance > best:
                best, index = distance, i
        if best > tolerance:
            keep[index] = True
            stack += [(a, index), (index, b)]
    return [p for p, k in zip(points, keep) if k]


def area(ring):
    return abs(sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(ring, ring[1:] + ring[:1]))) / 2


def main():
    with urllib.request.urlopen(SOURCE, timeout=30) as response:
        features = json.load(response)["features"]

    def polygons(feature):
        geometry = feature["geometry"]
        return [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]

    # Equirectangular projection corrected for Germany's mean latitude.
    k = math.cos(math.radians(51.2))
    rings = [ring for f in features for poly in polygons(f) for ring in poly]
    xs = [lon * k for ring in rings for lon, _ in ring]
    ys = [-lat for ring in rings for _, lat in ring]
    minx, miny = min(xs), min(ys)
    scale = WIDTH / (max(xs) - minx)
    height = (max(ys) - miny) * scale

    def project(ring):
        return [((lon * k - minx) * scale, (-lat - miny) * scale) for lon, lat in ring]

    states = []
    for feature in features:
        props = feature["properties"]
        parts = [[project(ring) for ring in poly] for poly in polygons(feature)]
        largest = max(area(poly[0]) for poly in parts)
        commands = []
        for poly in parts:
            if area(poly[0]) < largest * MIN_PART_RATIO:
                continue
            for ring in poly:
                # Closed rings start and end on the same point, which gives
                # Douglas-Peucker no baseline; simplify each half separately.
                half = len(ring) // 2
                ring = simplify(ring[:half + 1], TOLERANCE)[:-1] + simplify(ring[half:], TOLERANCE)
                if len(ring) < 4:
                    continue
                commands.append("M" + "L".join("%.1f %.1f" % p for p in ring[:-1]) + "Z")
        states.append({
            "id": props["id"],
            "name": props["name"],
            "parliament": PARLIAMENTS[props["id"]],
            "path": "".join(commands),
        })

    # City states sit inside their neighbours; draw (and hit-test) them last.
    states.sort(key=lambda s: s["id"] in ("DE-BE", "DE-HB", "DE-HH"))
    print(".pragma library")
    print("// Generated by tools/build-map.py from deutschlandGeoJSON (isellsoap). Do not edit.")
    print("var width = %.1f" % WIDTH)
    print("var height = %.1f" % height)
    print("var states = " + json.dumps(states, ensure_ascii=False, indent=1))


main()
